
const GOT_ERROR = 'GOT_ERROR';
const ADD_TECH_DOMAIN = 'ADD_TECH_DOMAIN';
const ADDED_NEW_TECH_DOMAIN = 'ADDED_NEW_TECH_DOMAIN';
const LOAD_TECH_DOMAIN_COLLN = 'LOAD_TECH_DOMAIN_COLLN';
const LOADED_TECH_DOMAIN_COLLN = 'LOADED_TECH_DOMAIN_COLLN';

export default {
	GOT_ERROR,
	ADD_TECH_DOMAIN,
	ADDED_NEW_TECH_DOMAIN,
	LOAD_TECH_DOMAIN_COLLN,
	LOADED_TECH_DOMAIN_COLLN
}
